version: '3.7'
services:

  # ldap server configuration
  ldap-server:
    container_name: ldap_server_c
    build: ./
    environment:
      LDAP_ADMIN_PASSWORD: 123456
      LDAP_BASE_DN: dc=grow,dc=app
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - app-network

  # ldap admin web interface configuration
  ldap-admin:
    image: "osixia/phpldapadmin:latest"
    container_name: ldap_admin_c
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-server
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - 8090:80
    networks:
      - app-network
    
volumes:
  ldap_data:
  ldap_config:

networks:
  app-network:
    driver: bridge
    name: app-network
